name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
jobs:
  job1:
      name: Build action
      runs-on: ubuntu-latest
      outputs:
        output1: ${{steps.step1.outputs.test}}
        output2: ${{steps.step2.outputs.test}}
      steps:
        - id: step1
          run: echo "test=hello" >> $GITHUB_OUTPUT
        - id: step2
          run: echo "test=world" >> $GITHUB_OUTPUT
        - id: step3
          run: echo "${{steps.step1.outputs.test}}" 
  job2:
      name: Build action
      runs-on: ubuntu-latest
      needs: job1
      steps:
        - id: step1
          run: echo "${{needs.job1.outputs.output1}}" 




# name: CI
# # Controls when the workflow will run
# on:
#   workflow_dispatch:
#   # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: ["main"]
# jobs:
#   name_checkout:
#     name: Build action
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#         id: tagname
#       - name: "Checkout"
#         run: |
#           git checkout -b "new_branch"
#       - name: "Echo"
#         run: |
#           echo "${{ fromJson(steps.tagname.outputs)}}"
